# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1,26.2)
neo_version=26.1.2.76
neo_version_range=[26.1,)
loader_version_range=[5,)

## Mod Properties
mod_id=tinypipes
mod_name=Tiny Pipes
mod_license=GNU GENERAL PUBLIC LICENSE
mod_version=26.1-6.1.1
mod_group_id=com.dannyandson.tinypipes
mod_authors=Danny
mod_description=Advanced pipes for transfer of items, energy and redstone that can share the same block space.